# Generated by Django 2.2.4 on 2019-08-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activo', models.CharField(choices=[('s', 'Activo'), ('n', 'Inactivo')], max_length=2)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
