# Generated by Django 2.2.4 on 2019-08-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
