# Generated by Django 2.2.4 on 2019-08-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0002_municipio_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('codigo', models.IntegerField(unique=True)),
            ],
        ),
    ]
