# Generated by Django 2.2.4 on 2019-08-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='municipios',
            field=models.ManyToManyField(to='col.municipio'),
        ),
    ]
