# Generated by Django 2.2.4 on 2019-08-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0004_region_municipios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
