# Generated by Django 2.2.4 on 2019-08-11 04:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('col', '0005_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='municipio',
            new_name='municipioA',
        ),
        migrations.RenameModel(
            old_name='region',
            new_name='regionA',
        ),
    ]
