# Generated by Django 2.2.4 on 2019-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0006_auto_20190810_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.CharField(choices=[('s', 'Activo'), ('n', 'Inactivo')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
