# Generated by Django 2.2.4 on 2019-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0007_auto_20190811_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='is_active',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='municipioa',
            name='is_activo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=2),
        ),
    ]
