# Generated by Django 2.2.4 on 2019-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0008_auto_20190811_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipioa',
            name='is_activo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10),
        ),
    ]
