# Generated by Django 2.2.4 on 2019-08-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0011_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiona',
            name='municipios',
        ),
        migrations.AlterField(
            model_name='region',
            name='municipios',
            field=models.ManyToManyField(blank=True, to='col.Municipio'),
        ),
        migrations.DeleteModel(
            name='municipioA',
        ),
        migrations.DeleteModel(
            name='regionA',
        ),
    ]
